name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['3.12']

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: install flake8
        run: |
          python3 -m pipx install --upgrade pip
          pipx install flake8

      - name: run flake8
        run: |
          flake8 app.py

  testing:
    needs: linting
    runs-on: ubuntu-latest

    steps:

      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: run unit test
        run: |
          python3 -m unittest discover
